name: MoreMaterials
version: 1.7.1
description: Custom blocks and items!
authors: [ZNickq, IceReaper, Runeko]
website: http://www.morematerials.net

depend: [Spout]
softdepend: [Furnace Api]
main: net.morematerials.Main

commands:
  mm:
    description: Some basic commands!
    usage: /<command> [?]
  mmgive:
    description: Gives you a custom material.
    usage: /<command> [custom material] {amount}
    permission: morematerials.give
  mmadmin:
    description: Internal helper functions.
    usage: |
      /<command> [list] - List all currently installed smp files.
      /<command> [updates] - List all updatable smp files.
      /<command> [install] [smpPackage] {version} - Install specified smp file in specified version (Defaults to latest).
      /<command> [uninstall] [smpPackage] - Uninstall specified smp file.
    permission: morematerials.admin

permissions:
  morematerials.*:
    description: Allows access to all of MoreMaterials' functionality.
    default: op
    children:
      morematerials.admin: true
      morematerials.craft.*: true
  morematerials.admin:
    description: Access to smp commands.
    default: op
    children:
      morematerials.give: true
  morematerials.give:
    description: Allows spawning MoreMaterials blocks and items.
    default: op
  morematerials.craft:
    description: Allows crafting of MoreMaterials blocks and items.
    default: true
    children:
      morematerials.craft.material: true
